# Generated by Django 4.1.5 on 2023-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_room_amenities_alter_room_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
