# Generated by Django 4.1.5 on 2023-01-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_experience_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="addres",
            new_name="address",
        ),
    ]
