# Generated by Django 4.1.5 on 2023-01-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0005_alter_experience_category_alter_experience_host_and_more",
        ),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="experience",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="experiences.experience",
            ),
        ),
    ]
